### ISSUE TITLE
Os.path issues

### ISSUE THREAD

**Issue by phamduyphat** [FireRedz/osr2png#5]
<h1> Issue: </h1>
 - Beatmaps with these chars '*', '<', '>' will break PIL.
<h1> Suggestion: </h1>
 - Add a -o option for custom output.

**Comment by xjunko** [comment]
Niceeee, I'm able to reproduce it on my end, will fix!
As for the suggestions, I will also implement those.

Many thanks!

https://user-images.githubusercontent.com/44401509/219856304-35658536-8591-4abb-a2e9-ec141146a4a8.mp4

**Comment by xjunko** [comment]
Should be fixed now, da718c4549e063b7cda3e166bb5e25e3b6b86aae and 84fff4c60dd09faf0a0707d205172c09142d138f.

https://github.com/xjunko/osr2png/releases/tag/0.7.7
