### ISSUE TITLE
Windows binaries still downloading 0.7.7?

### ISSUE THREAD

**Issue by fleuph** [FireRedz/osr2png#9]
Downloaded latest release from releases page. When running commands the version detector returns version 0.7.7 and asks for update.

**Comment by xjunko** [comment]
weird, are you sure you downloaded the latest version.
https://github.com/xjunko/osr2png/releases/tag/0.7.8

**Comment by fleuph** [comment]
100% certain. I just redownloaded from the given link and tried again. This is what I see.
![image](https://github.com/xjunko/osr2png/assets/172005410/406ed38d-5c4a-4963-bfd9-9fc55032ac23)

**Comment by fleuph** [comment]
Never makes it past that line either.

**Comment by xjunko** [comment]
Yep, replicable, seems like the release build is older for some reason. 
Also, the CDN is broken so I fixed that too, and updated the pp library so should be working fine now.

[Release 0.7.9](https://github.com/xjunko/osr2png/releases/tag/0.7.9)
